
name: Run Python Tests
on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install coverage
          sudo apt install stockfish
          pip install stockfish
      - name: Test with unittest
        run: | 
          python -m unittest -v
